version : "3"
services:
  my-movie-app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=****
      - MYSQL_DATABASE=filmapp
  redis-server:
    hostname: redis
    image: 'redis'
    ports:
    - "6379:6379"

  my-movie-app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - my-movie-app-db
      - redis-server

